import fs from 'node:fs';
import path from 'node:path';
const origin='https://explorenovapath.com';
const root='client/public';
const pages=JSON.parse(fs.readFileSync('content/guides/pages.json','utf8'));
const topics={compensation:{name:'Wage & compensation',description:'Prepare your study, understand the analysis, and evaluate the findings.',service:'wage-compensation-studies'},coaching:{name:'CoachingOS & coaching practice',description:'Connect observations, actions, and follow-through in a repeatable coaching routine.',service:'coachingos'},training:{name:'Staff training & completion',description:'Define learning goals, review content, and distinguish completion from application.',service:'training-compliance-courses'}};
topics.software={name:'Custom software',description:'Define the workflow, compare approaches, and scope a useful first release.',service:'custom-software'};
topics.advisory={name:'Strategic advisory',description:'Clarify priorities, map the work, and plan your next decision.',service:'strategic-advisory'};
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const url=slug=>`${origin}/guides/${slug}/`;
const json=x=>JSON.stringify(x).replaceAll('<','\\u003c');
const org={'@type':'Organization','@id':`${origin}/#organization`,name:'NovaPath',url:origin};
function crumbs(items){return {'@type':'BreadcrumbList',itemListElement:items.map((x,i)=>({'@type':'ListItem',position:i+1,name:x[0],item:x[1]}))};}
function write(slug,title,description,body,schema,breadcrumbs=[]){
 const canonical=slug?url(slug):`${origin}/guides/`;
 const nav=breadcrumbs.map(([label,href])=>`<a href="${href}">${esc(label)}</a>`).join(' <span aria-hidden="true">/</span> ');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | NovaPath</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="${schema['@type']==='Article'?'article':'website'}"><link rel="stylesheet" href="/service-pages.css"><link rel="icon" href="/brand/favicon.svg"><script src="/discovery.js" defer></script><script src="/analytics.js" defer></script><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':[org,schema,crumbs([...breadcrumbs,[title,canonical]])]})}</script></head><body><a class="skip" href="#main">Skip to content</a><header><div class="wrap"><a class="brand" href="/"><img src="/brand/np-mark.svg" alt="">NovaPath</a><a href="/guides/">Buyer guides</a></div></header><main id="main" class="wrap service-main"><nav class="breadcrumbs" aria-label="Breadcrumb">${nav}</nav>${body}</main><footer><div class="wrap"><a href="/">NovaPath</a> · <a href="/about">About NovaPath</a> · <a href="mailto:hello@explorenovapath.com">hello@explorenovapath.com</a></div></footer></body></html>`;
 const dir=path.join(root,'guides',slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);
}
function cards(list){return `<div class="guide-cards">${list.map(p=>`<section><h2><a href="/guides/${p.slug}/">${esc(p.title)}</a></h2><p>${esc(p.description)}</p></section>`).join('')}</div>`;}
for(const p of pages){
 if(!topics[p.topic]||!p.body.includes('<section>'))throw Error(`Invalid guide ${p.slug}`);
 const topic=topics[p.topic];let i=0;const toc=[];
 const body=p.body.replace(/<h2>(.*?)<\/h2>/g,(_,title)=>{const id=`section-${++i}`;toc.push(`<li><a href="#${id}">${title}</a></li>`);return `<h2 id="${id}">${title}</h2>`;});
 const related=pages.filter(x=>x.topic===p.topic&&x.slug!==p.slug).slice(0,4);
 write(p.slug,p.title,p.description,`<article><p class="eyebrow">${esc(topic.name)} · Buyer guide</p><h1>${esc(p.title)}</h1><p class="terms">By <a href="/about">NovaPath</a> · Published <time datetime="2026-09-11">September 11, 2026</time></p><nav class="on-this-page" aria-label="On this page"><strong>On this page</strong><ol>${toc.join('')}</ol></nav>${body}<section class="guide-next"><h2>Discuss your needs</h2><p>Share your goals, scope, and deadline through our inquiry form.</p><a class="button" href="/#contact">Start a conversation</a><p><a href="/${topic.service}/">Explore ${esc(topic.name)}</a></p></section></article><nav aria-label="Related guides"><h2>Continue exploring</h2><ul>${related.map(x=>`<li><a href="/guides/${x.slug}/">${esc(x.title)}</a></li>`).join('')}<li><a href="/guides/${p.topic}/">All ${esc(topic.name.toLowerCase())} guides</a></li></ul></nav>`,{'@type':'Article',headline:p.title,description:p.description,mainEntityOfPage:url(p.slug),datePublished:'2026-09-11',author:org,publisher:org,isPartOf:{'@id':url(p.topic)}},[['Home',origin+'/'],['Buyer guides',origin+'/guides/'],[topic.name,url(p.topic)]]);
}
for(const [slug,t] of Object.entries(topics)){const list=pages.filter(x=>x.topic===slug);write(slug,t.name+' guides',t.description,`<p class="eyebrow">Resource collection</p><h1>${esc(t.name)} guides</h1><p class="intro">${esc(t.description)}</p><p><a href="/${t.service}/">Explore the service</a></p>${cards(list)}`,{'@type':'CollectionPage','@id':url(slug),name:t.name+' guides',url:url(slug),hasPart:list.map(p=>({'@type':'Article',headline:p.title,url:url(p.slug)}))},[['Home',origin+'/'],['Buyer guides',origin+'/guides/']]);}
write('','Software, Advisory, Compensation & Training Guides','Methodology, examples, checklists, and practical buying guidance for Head Start programs, schools, and nonprofits.',`<p class="eyebrow">NovaPath resource library</p><h1>Clearer evidence. Better decisions.</h1><p class="intro">Practical guidance for choosing software, planning organizational change, evaluating compensation, connecting coaching work, and preparing staff training.</p>${Object.entries(topics).map(([slug,t])=>`<section><h2><a href="/guides/${slug}/">${esc(t.name)}</a></h2><p>${esc(t.description)}</p><ul>${pages.filter(p=>p.topic===slug).map(p=>`<li><a href="/guides/${p.slug}/">${esc(p.title)}</a></li>`).join('')}</ul></section>`).join('')}<section><h2>About these resources</h2><p>Published by NovaPath to help teams evaluate scope and prepare decisions. Illustrative examples are labeled. Engagement deliverables, fees, and implementation requirements are confirmed in a written scope. <a href="/about">Learn about NovaPath.</a></p></section>`,{'@type':'CollectionPage',name:'NovaPath buyer guides',url:origin+'/guides/',hasPart:Object.keys(topics).map(slug=>({'@id':url(slug)}))},[['Home',origin+'/']]);
// Discover all static public pages and actual blog slugs; exclude noindex pages.
const urls=new Set(['/', '/about','/cobuilder','/blog']);
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(e.name==='index.html'&&!/noindex/i.test(fs.readFileSync(p,'utf8'))){urls.add('/'+path.relative(root,path.dirname(p)).split(path.sep).filter(Boolean).join('/')+'/');}}}
walk(root);
for(const f of fs.readdirSync('content/blog')){if(f.endsWith('.md')){const slug=fs.readFileSync('content/blog/'+f,'utf8').match(/^slug: (.+)$/m)?.[1];if(slug)urls.add('/blog/'+slug);}}
fs.writeFileSync(root+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${[...urls].sort().map(p=>`  <url><loc>${origin}${p}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Built ${pages.length} guides, ${Object.keys(topics).length} topic hubs, and ${urls.size} sitemap URLs.`);
